# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' generates one draw from type probability distribution for each type in P
#'
#' @param P parameter_matrix of parameters and causal types
#' @param parameters, priors or posteriors
#' @return draw from type distribution for each type in P
get_type_prob_c <- function(P, parameters) {
    .Call(`_CQBigModel_get_type_prob_c`, P, parameters)
}

#' generates n draws from type probability distribution for each type in P
#'
#' @param params parameters, priors or posteriors
#' @param P parameter_matrix of parameters and causal types
#' @return draws from type distribution for each type in P
get_type_prob_multiple_c <- function(params, P) {
    .Call(`_CQBigModel_get_type_prob_multiple_c`, params, P)
}

#' generates one draw from type probability distribution for each type in P
#'
#' @param P parameter_matrix of parameters and causal types
#' @param parameters, priors or posteriors
#' @param nrow number of rows in P
#' @param ncol number of columns in P
#' @return draw from type distribution for each type in P
get_type_prob_cstd <- function(P, parameters, nrow, ncol) {
    .Call(`_CQBigModel_get_type_prob_cstd`, P, parameters, nrow, ncol)
}

#' generates n draws from type probability distribution for each type in P
#'
#' @param params parameters, priors or posteriors
#' @param P parameter_matrix of parameters and causal types
#' @param nrow number of rows in params matrix before being flattend to vector
#' @param ncol numbers of columns in params matrix before being flattened to vector
#' @param nrow_p number of rows in P matrix before being flattened to vector
#' @param ncol_p number of columns in P matrix befroe being flattened to vector
#' @return draws from type distribution for each type in P
get_type_prob_multiple_cstd <- function(params, P, nrow, ncol, nrow_p, ncol_p) {
    .Call(`_CQBigModel_get_type_prob_multiple_cstd`, params, P, nrow, ncol, nrow_p, ncol_p)
}

#' cpp implementation of realise_outcomes. Realise outcomes for all causal types.
#' Calculated by sequentially calculating endogenous nodes. If a do operator is applied to
#' any node then it takes the given value and all its descendants are generated accordingly.
#' Output is written to a bigmatrix.
#'
#' @param outcomes memory address of a bigmatrix object
#' @param nodes string vector of nodes names
#' @param endogenous_nodes string vector of endogenous nodes
#' @param dos List of do operations
#' @param parents_list List of parent nodes for each node
#' @param nodal_types List of integer matrices with uncollapsed nodal types
#' @param nodal_types_colnames List of column names of matrices in nodal_types
#' @param nodal_types_collapsed List of collapsed nodal types
#' @param n_causal_types int specifying number of causal types
realise_outcomes_c <- function(outcomes, nodes, endogenous_nodes, dos, parents_list, nodal_types, nodal_types_colnames, nodal_types_collapsed, n_causal_types) {
    invisible(.Call(`_CQBigModel_realise_outcomes_c`, outcomes, nodes, endogenous_nodes, dos, parents_list, nodal_types, nodal_types_colnames, nodal_types_collapsed, n_causal_types))
}

#' cpp implementation of realise_outcomes for map_query_to_causal_types. Dos are evaluated
#' and the realised outcomes for the variable they are attached to is written to a bigmatrix.
#'
#' @param nodes string vector of nodes names
#' @param endogenous_nodes string vector of endogenous nodes
#' @param dos List of do operations
#' @param parents_list List of parent nodes for each node
#' @param nodal_types List of integer matrices with uncollapsed nodal types
#' @param nodal_types_colnames List of column names of matrices in nodal_types
#' @param nodal_types_collapsed List of collapsed nodal types
#' @param n_causal_types int specifying number of causal types
#' @param vars string vector with names of variables dos are attached to
query_to_ct_c <- function(nodes, endogenous_nodes, dos, parents_list, nodal_types, nodal_types_colnames, nodal_types_collapsed, n_causal_types, vars) {
    .Call(`_CQBigModel_query_to_ct_c`, nodes, endogenous_nodes, dos, parents_list, nodal_types, nodal_types_colnames, nodal_types_collapsed, n_causal_types, vars)
}

