# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' generates one draw from type probability distribution for each type in P
#'
#' @param P parameter_matrix of parameters and causal types
#' @param parameters, priors or posteriors
#' @return draw from type distribution for each type in P
get_type_prob_c <- function(P, parameters) {
    .Call(`_CQBigModel_get_type_prob_c`, P, parameters)
}

#' generates n draws from type probability distribution for each type in P
#'
#' @param params parameters, priors or posteriors
#' @param P parameter_matrix of parameters and causal types
#' @return draws from type distribution for each type in P
get_type_prob_multiple_c <- function(params, P) {
    .Call(`_CQBigModel_get_type_prob_multiple_c`, params, P)
}

#' generates one draw from type probability distribution for each type in P
#'
#' @param P parameter_matrix of parameters and causal types
#' @param parameters, priors or posteriors
#' @param nrow number of rows in P
#' @param ncol number of columns in P
#' @return draw from type distribution for each type in P
get_type_prob_cstd <- function(P, parameters, nrow, ncol) {
    .Call(`_CQBigModel_get_type_prob_cstd`, P, parameters, nrow, ncol)
}

#' generates n draws from type probability distribution for each type in P
#'
#' @param params parameters, priors or posteriors
#' @param P parameter_matrix of parameters and causal types
#' @param nrow number of rows in params matrix before being flattend to vector
#' @param ncol numbers of columns in params matrix before being flattened to vector
#' @param nrow_p number of rows in P matrix before being flattened to vector
#' @param ncol_p number of columns in P matrix befroe being flattened to vector
#' @return draws from type distribution for each type in P
get_type_prob_multiple_cstd <- function(params, P, nrow, ncol, nrow_p, ncol_p) {
    .Call(`_CQBigModel_get_type_prob_multiple_cstd`, params, P, nrow, ncol, nrow_p, ncol_p)
}

#' Determines the number of times each nodes' vector of nodal types is repeated to generate the pattern of causal types.
#' Combining this information with the position of a causal type allows us to determine the nodal types used in the construction
#' of the given causal type.
#'
#' parameter nodal_types a List of nodal types
#' parameter nodes string vector of node names
#' return a map of node names and an integer of repetitions for each nodes' nodal type vector
NULL

